language: objective-c
osx_image: xcode7.3

env:
  - "DESTINATION='platform=iOS Simulator,name=iPhone 6S' ACTION=build"
  - "DESTINATION='platform=OS X' ACTION=build"
  - "DESTINATION='platform=tvOS Simulator,name=Apple TV 1080p' ACTION=build"

script:
  - set -o pipefail && xcodebuild -scheme FlagKit -destination "$DESTINATION" $ACTION | xcpretty
